[package]
name = "tst"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.16"
chrono = "0.4"
num-traits = "0.2"
egui-datepicker = "0.3"